# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ServiceQualityMicro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ca8b2be942c7421e97b2fa3cae6198e4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b778f6d77b6340088ad4bf48591c401c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ca8b2be942c7421e97b2fa3cae6198e4 }}/nestjs-service-qualityapi-dev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ServiceQualityMicro'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c96e0091ca89434d911c59862a72f31b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ca8b2be942c7421e97b2fa3cae6198e4 }}/nestjs-service-qualityapi-dev:${{ github.sha }}'