# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ServiceQualityMicroservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_bfd923ccadb545fdad95c22f6d4d81a3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9027a9ce71d54bc4939609cd8e186be2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bfd923ccadb545fdad95c22f6d4d81a3 }}/nestjs-service-qualityapi-dev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ServiceQualityMicroservice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4d3969c890bf4aa2baa4568264463afe }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bfd923ccadb545fdad95c22f6d4d81a3 }}/nestjs-service-qualityapi-dev:${{ github.sha }}'